### ISSUE TITLE
Question: How to set this progress while loading instead of Glide-image?

### ISSUE THREAD

**Issue by Rainer-Lang** [JessYanCoding/ProgressManager#1]
Is it possible to show this progress control while Glide is loading the image - and then replace the progress with the downloaded image?
Could you add an example?

**Comment by JessYanCoding** [comment]
Replace？what is mean？

**Comment by Rainer-Lang** [comment]
While image is loading show your progress-lib - and when image is loaded set your progress GONE and show loaded image.

**Comment by JessYanCoding** [comment]
This is not ui library

**Comment by Rainer-Lang** [comment]
I found a solution with Glide-listener. For now I only show a normal ProgressBar. Maybe in future I'll use your lib - because the loading of my images is so fast - user will see nothing of the progress.
