### ISSUE TITLE
viewpager+photovie进度错乱

### ISSUE THREAD

**Issue by zhupengxiang** [JessYanCoding/ProgressManager#10]
我在viewpager+photoview监听进度是  progressbar的进度错乱 进度一会大一会小  知道什么原因造成的

**Comment by JessYanCoding** [comment]
多半是一个进度条，监听了两个正在进行的进度，progressinfo里面有id,你自己打印出来，看是不是同时存在多个不同的id的进度在执行

**Comment by zhupengxiang** [comment]
@ viewpager有预加载  这种情况 我打印肯定有另个监听  但进度条也是有两个呀

**Comment by JessYanCoding** [comment]
你不管进度条有几个,你要看一个进度条监听了几个正在进行的进度，自己打印id看

**Comment by zhupengxiang** [comment]
@JessYanCoding  嗯我试试看

**Comment by zhupengxiang** [comment]
@JessYanCoding  我昨天试了 viewpager中放imageview监听  我vp现在只有一个imageview 相当于监听了一个path 但是我在onProgress中打印 id有两个  这是什么情况导致的

**Comment by JessYanCoding** [comment]
这个就不知道了,是和你业务逻辑有关了,是你自己的操作导致了一个监听器同时监听了两个正在进行的进度,第一个进度值大,第二个进度值小,当然是跳来跳去,所以这不是框架的问题

**Comment by zhupengxiang** [comment]
@JessYanCoding   大佬我想问怎么解决呀在vp中  我就是在instantiateItem中按照demo的glide监听弄的

**Comment by JessYanCoding** [comment]
...,这个你只有自己一个个debug,看到底是为什么触发了两次请求,应该不难吧,和你业务逻辑又关,自己解决
