### ISSUE TITLE
上传文件进度监听的URL有什么规定吗？

### ISSUE THREAD

**Issue by HolickABC** [JessYanCoding/ProgressManager#11]
我上传文件到  http://bbetter.lianhezichan.com/file/upload/  
相应的URL也写成这个  但是progressListener没有被调用

**Comment by JessYanCoding** [comment]
上传成功,没调用进度？你要看看 **Okhttp** 是否是执行了你的上传请求

**Comment by HolickABC** [comment]
HttpLoggingInterceptor打印出来是执行了上传请求并且上传成功。
还是说我URL拼接有问题呢？这是接口文档
<img width="711" alt="wx20170828-115211 2x" src="https://user-images.githubusercontent.com/22294596/29758600-6172a340-8be7-11e7-9407-c0014f745c0a.png">

**Comment by JessYanCoding** [comment]
你要确定服务器上是否有你的文件,才能确定是否上传成功,如果真的上传成功,那你要换个其他的的上传接口,看看是否只是这个服务器进度监听不了,还是所有服务器都不行,因为我只是利用了 **Okhttp** 监听器,监听器正确设置后,只要 **Okhttp** 是请求了这个接口的,是不可能不调用他自己的监听器的,除非遇到什么错误

**Comment by HolickABC** [comment]
好的  谢谢
