### ISSUE TITLE
关于注册监听器回收的问题

### ISSUE THREAD

**Issue by ChengangFeng** [JessYanCoding/ProgressManager#13]
你好，我看了一下您实现的源码里面，在`ProgressManager.java`这个类里面，对上传或者下载的`ProgressListener`统一放到`WeakHashMap`中进行处理。

此处，我想问，在注册了监听器后，因为`WeakHashMap`会对没有引用到的key，将其跟value一并回收了，所以在注册了监听器后的这段时间内，恰好GC回收，我觉得可能存在某些监听器也会被回收了，因为代码里面好像没看到哪里引用了这些key，所以我觉得有可能导致进度回调不了。

这是我的一点点疑问，也有可能我忽略了代码中某些重要地方，所以想问一下。

**Comment by JessYanCoding** [comment]
建议你自己用 Demo 做下测试,使用 Android Studio 自带的 Monitors 手动 GC,看看结果怎样,是否就无法监听了？

**Comment by JessYanCoding** [comment]
因为 `WeakHashMap` 将 **key** 作为弱键,所以当系统 **GC** 时的确会将某个不在被引用的 **key** 加入 `ReferenceQueue`, 在下一次操作 `WeakHashMap` 时,会比对 `ReferenceQueue` 中的 **key**, 将 `WeakHashMap` 中对应 **key** 连同 **value** 一起移除,但是因为我演示的 Demo 中用的是全局静态常量,所以这个 **key** 是永远都不会被加入 `ReferenceQueue` 的

**Comment by JessYanCoding** [comment]
所以在你们日常使用中,这个 **key** 必须和对应的 **Activity/Fragment** 生命周期同步,也就是用全局变量持有,最重要的是使用 `String mUrl = new String("url");`, 而不是 `String mUrl = "url";`

**Comment by ChengangFeng** [comment]
got it, 谢谢你的解答
