### ISSUE TITLE
请问如何监听get请求的进度？

### ISSUE THREAD

**Issue by jayleco** [JessYanCoding/ProgressManager#14]
比如使用okhttp请求一个网页，如：https://github.com/JessYanCoding 如何实现获取请求这个网页的进度？
我看了下demo好像只有文件下载和上传以及glide的进度监听啊

说实话，你这个项目帮了我大忙，节省了我这个菜鸟大量的工作时间，感谢作者

**Comment by JessYanCoding** [comment]
加载一个网页的进度是浏览器的需求,这个框架和你怎么请求无关,只要你用 **Okhttp** 或者 **Retrofit** 进行请求,并且服务器返回了 body 就可以读取进度

**Comment by jayleco** [comment]
@JessYanCoding 不是浏览器需求，我是通过okhttp请求网页，获取html代码

**Comment by JessYanCoding** [comment]
和 Demo 的用法一样

**Comment by jayleco** [comment]
好的，谢谢!
