### ISSUE TITLE
viewPager中滑动出现进度条没到100就停下了，但是图片却已经显示出来了

### ISSUE THREAD

**Issue by jayleco** [JessYanCoding/ProgressManager#15]
我使用了viewPager滑动来做为组图浏览，item里有一个imageView和一个progressBar，运行后滑动翻页会出现progressBar挺住不动了但是图片却已经显示出来了

**Comment by JessYanCoding** [comment]
Glide?是在百分0到100的过程中,停到中间还是直接就是0一直没动, Glide 会涉及到缓存的问题, 只有自己解决

**Comment by jayleco** [comment]
item.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.github.chrisbanes.photoview.PhotoView
        android:id="@+id/photo_pv"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />

    <ProgressBar
        android:id="@+id/progressBar"
        style="?android:attr/progressBarStyleHorizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_marginRight="10dp"
        android:max="100"
        android:progress="0" />
</LinearLayout>`

adapter.java

`public class SubDetailImageAdapter extends PagerAdapter {
    private static final String TAG = "OK";
    private Context context;
    private View view;
    private List data;
    private LayoutInflater inflater;
    private  private ProgressBar progressBar;
    private Handler mHandler;
    public SubDetailImageAdapter(Context context, List data) {
        this.context = context;
        this.data = data;
        this.inflater = LayoutInflater.from(context);
        mHandler = new Handler();
    }

    @Override
    public int getCount() {
        return data.size();
    }

    @Override
    public boolean isViewFromObject(View view, Object object) {
        return view == object;
    }

    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        //super.destroyItem(container, position, object);
        container.removeView((View) object);
    }

    @Override
    public Object instantiateItem(ViewGroup container, int position) {
        view = inflater.inflate(R.layout.item_sub_detail_img, null);
        PhotoView photoView = view.findViewById(R.id.photo_pv);
        progressBar = view.findViewById(R.id.progressBar);
        String image_url = (String) data.get(position);
        ProgressManager.getInstance().addResponseListener(image_url, getGlideListener());
        GlideApp.with(context).load(image_url)
                .fitCenter()
                .into(photoView);
        container.addView(view);

        return view;
    }

    @NonNull
    private ProgressListener getGlideListener() {
        return new ProgressListener() {
            @Override
            public void onProgress(ProgressInfo progressInfo) {
                int progress = progressInfo.getPercent();
                progressBar.setProgress(progress);
                Log.d(TAG, "--Glide-- " + progress + " %  " + progressInfo.getSpeed() + " byte/s  " + progressInfo.toString());
                if (progressInfo.isFinish()) {
                    //说明已经加载完成
                    Log.d(TAG, "--Glide-- finish");
                }
            }

            @Override
            public void onError(long id, Exception e) {
                mHandler.post(new Runnable() {
                    @Override
                    public void run() {
                        progressBar.setProgress(0);
                    }
                });
            }
        };
    }
}`

**Comment by jayleco** [comment]
@JessYanCoding  停在不定的位置，如百分之三十几，五十几等等

**Comment by JessYanCoding** [comment]
你这样有问题啊, ProgressManager.getInstance().addResponseListener, 只能初始化一次,最好放在Adapter 的构造函数中

**Comment by jayleco** [comment]
glide，我没设置磁盘缓存，而且图片都是第一次加载

**Comment by JessYanCoding** [comment]
不翻页就没问题把

**Comment by jayleco** [comment]
不翻页也会有这个问题，ProgressManager.getInstance().addResponseListener放在构造函数里面的话怎么给他传当前位置的URL呢

**Comment by jayleco** [comment]
构造函数里先给他new一个ProgressManager吗？

**Comment by jayleco** [comment]
我在一个RecyclerView的图片列表里使用也有这个问题

**Comment by JessYanCoding** [comment]
你最好把断点打到 ProgressResponseBody 里面, 看看里面的二进制到底是没有下载完, 还是下载完了框架没通知, 不然我也没办法解决

**Comment by zhupengxiang** [comment]
@jayleco   我以前用这个在viewpager也是这个问题 进度错乱  你现在解决了么
