### ISSUE TITLE
看清楚别人写的什么再去发广告，ok？

### ISSUE THREAD

**Issue by a1018875550** [JessYanCoding/ProgressManager#16]
我写的‘’ Retrofit+Rxjava 下载文件(带进度显示)’ 跟你这个有关系么，广告乱发至于么，想出名想疯了把，；

**Comment by JessYanCoding** [comment]
抱歉, 不满意删了就是

**Comment by JessYanCoding** [comment]
至于您说的, 我想靠评论您的文章从而出名, 其实你大可不必有这个想法, 我只作为一个狂热的开源爱好者下, 单纯的分享而已, 如果您觉得我的回答不能让您信服, 那可以用一下数据证明:

* 对于个人
** 我这个 **Github** 账号自己创建并维护的所有个人项目的 **Stars** 加起来, 10几倍于你的这个 **Github** 账号
** 我这个 **Github** 账号的 **Followers** 10几倍于你的这个 **Github** 账号
** **CSDN** 这个平台我很少逛, 主要在简书和掘金者两个平台, 两个平台的粉丝数加起来有 5000+, 发布文章比较少但总阅读量也是在 10W+ 以上
* 对于这个框架
** 在国内被 [张鸿洋](http://mp.weixin.qq.com/s/bopDUFMB7EiK-MhLc3KDXQ), [gank.io](http://gank.io/2017/06/12), [Android开发技术周报 ](http://www.androidweekly.cn/android-dev-weekly-issue-134/) 等多个平台被推荐
** 在国外被 [medium](https://medium.cobeisfresh.com/top-5-android-libraries-august-2017-6c1435f11f1e), [reddit](https://www.reddit.com/r/androiddev/comments/6kdbtx/any_tutorials_for_displaying_a_progress_bar_to/), [ Android Arsenal](https://android-arsenal.com/details/1/5865) 等多个平台被推荐

以上没有其他意思, 只是单纯的想证明 **想在你文章中打广告, 然后靠你的文章的人气从而出名, 真的从开始就一丁点这个想法都不成产生, 不要误会了**

**Comment by a1018875550** [comment]
怎么，那你是觉得我是故意来骂你发广告的，然后我要靠此事出名么？

**Comment by a1018875550** [comment]
发广告了，还这么有理的，第一次见了，厉害了，大神

**Comment by JessYanCoding** [comment]
@a1018875550 
1. 如果您觉得分享知识都叫做发广告, 那我写的所有文章那都是广告

2. 我上面对您写的所有内容, 不管是内容还是语气, 态度对您都做到了起码的尊敬, 并且也十分理性, 反倒是您的语言有点不善, 偏激和嘲讽, 沟通时心态不理性, 这样持续下去确实无法继续有效沟通

3. 程序员言语上挣个谁对谁错确实意义不大, 不如把这个时间用在学习和写代码上, 事实上我是认真看完了您文章中写的每一行代码, 才觉得您代码还可以再优化, 才分享了我的代码,  我对您的尊重, 也是觉得您也是在认真分享知识, 可能站在您的角度有觉得我的做法有点突兀, 但我觉得技术圈勇于纠错, 敢于分享这样的氛围并没有什么错

4. 我猜您过来这里发起这个 **Issues** 之前可能没认真看过这个库的代码, 我建议您有在 **Issues** 中和我争论的时间, 不如好好看看这里的代码, 了解下您的代码为什么需要优化, 这样对您也是有成长的, 比消耗大量时间拿来挣个谁对谁错更有意义

5. 我上面列举的所有数据, 已经证明如果在您那发广告对我来说是无意义的事情, 我只是在随意的分享知识, 您那的流量对我来说微乎其微, 事实上我这个库的后台统计根本没有来自您那里的流量, 如果我想争取流量我可以在写篇文章, 我没什么理由为了那微乎其微的流量发你所谓的广告而有损自己

如果我的回答影响到了您的心情或打扰到了您, 那我再一次表示抱歉🙏

**Comment by a1018875550** [comment]
是啊，语言上争论没用的，毕竟我才发了几句话你都发了好几篇作文了，而且每篇文章您都沾在圣人角度的至高点上，既然这样，那我承认了行了吧，大神？圣人？

**Comment by JessYanCoding** [comment]
随您怎么想吧, 我也说了以您现在这个心态, 和您争论是没什么意义的, 我打这么多字也是, 尊重您, 想和您认真沟通, 因为我觉得您也是在认真的分享知识,值得尊重, 如果一般的人发这么偏激的标题, 我内容都不会看, 更不会回复, 因为我的项目和文章使我接触的人很多, 让我知道很多人是没必要理睬的, 我也有很多开源以及工作上的事去处理

好了, 感谢您以上的回复, 您不必在回复了, 祝你身体健康, 心情愉快
