### ISSUE TITLE
现在版本是不支持Stick的吗？

### ISSUE THREAD

**Issue by Zweihui** [JessYanCoding/ProgressManager#19]
就是我在请求发起后，再去添加监听，是不会执行后来加进来的监听。
```java
protected Handler mHandler;
    protected int mRefreshTime;
    protected final ResponseBody mDelegate;
    protected final ProgressListener[] mListeners;
    protected final ProgressInfo mProgressInfo;
    private BufferedSource mBufferedSource;

    public ProgressResponseBody(Handler handler, ResponseBody responseBody, List<ProgressListener> listeners, int refreshTime) {
        this.mDelegate = responseBody;
        this.mListeners = listeners.toArray(new ProgressListener[listeners.size()]);
        this.mHandler = handler;
        this.mRefreshTime = refreshTime;
        this.mProgressInfo = new ProgressInfo(System.currentTimeMillis());
    }
```
这是我修改后的代码，是可以监听的，希望提供更优雅的解决方法
```java
protected Handler mHandler;
    protected int mRefreshTime;
    protected final ResponseBody mDelegate;
    protected List<ProgressListener>  mListeners;
    protected final ProgressInfo mProgressInfo;
    private BufferedSource mBufferedSource;

    public ProgressResponseBody(Handler handler, ResponseBody responseBody, List<ProgressListener> listeners, int refreshTime) {
        this.mDelegate = responseBody;
        this.mListeners = listeners;
        this.mHandler = handler;
        this.mRefreshTime = refreshTime;
        this.mProgressInfo = new ProgressInfo(System.currentTimeMillis());
    }
```

**Comment by JessYanCoding** [comment]
我故意这样设计的, 进度在开始时, 使用一个固定长度的数组, 代替可变长度的 **List**, 在通知进度需要循环遍历所有监听器的时候, 能提高性能, 并且因为进度通知的很频繁, 监听器遍历也就很频繁, 性能也就越可观, ** 所以在 Url 的某个进度结束前向这个 Url 添加的监听器是不能立即生效的, 只有在下一次新开启的进度才会生效**, 这是我在设计时就预料到的
任何东西都不可能完美, 我只能做一个取舍, 抱歉我不可能为了小量的需求, 而去影响大家的性能

**Comment by Zweihui** [comment]
我是在Service里开启下载监听，然后可以跳转Activity显示下载进度列表，这种需求场景应该还是有的。我觉得可以参考EventBus的粘性事件来设计。

**Comment by JessYanCoding** [comment]
上面已经说了, 为了性能考虑某个进度开启和结束期间, 这个进度需要通知的监听器数量是不可变的, 和粘性事件无关

**Comment by Zweihui** [comment]
额~我的意思是可以再维护一个粘性监听器集合，判断这个集合是否为空再去遍历，也就是如果有这个需求就用，不需要就不用，这样应该也算是兼顾了原功能的性能。

**Comment by JessYanCoding** [comment]
粘性事件的原理可以让事件的通知领先于注册, 那是因为注册的时候可以主动去拿出之前储存的事件并去调用立即执行, 但是这里监听器通知一直都是 **okhttp** 把握主动权, 进度通知只是被动的去遍历通知监听器, 粘性事件在这里根本不适用

**Comment by JessYanCoding** [comment]
一个进度信息的监听, 含有无数次进度的通知，一次进度通知, 会遍历一次监听器, 200ms 通知一次,一秒也就要遍历5次, 按你的说的我要保证正在执行的进度也要将后面加进来的监听器, 也要正常被通知到, 那我每次进度的更新都要去判断是否有新的监听器加入进来, 一秒要判断5次, 还不如用你的那个可变集合

**Comment by Zweihui** [comment]
ok 我只是提供一下我的想法，可以关闭了。么么哒

**Comment by JessYanCoding** [comment]
@Zweihui 你这个需求要实现也不一定要在 Activity 中去注册监听器, 就在 Service 中注册监听器然后在监听器中使用 eventbus 或者其他方式去通知需要监听进度的 UI 层, Service 承担下载和进度信息分发的工作, 这样就算同时通知多个 Activity 和 Fragment 都可以实现, 对各种进度信息的统一管理与分发随着业务的增长好处也越可观, 也不用改源码就能实现你的需求

**Comment by Zweihui** [comment]
嗯 好的，谢谢
