### ISSUE TITLE
Crash:OutOfMemoryError when download large file

### ISSUE THREAD

**Issue by hurshi** [JessYanCoding/ProgressManager#2]
OutOfMemoryError when I download a large file about more than 2GB
下载大文件的时候貌似是不能使用这种拦截器的，拦截器会把下载下来的都缓存在内存中，直到OutOfMemory；可以在流转换成文件时实现进度更新: http://t.cn/RS3PcUa

**Comment by JessYanCoding** [comment]
本库的优点就在于调用简单,可插拔,侵入性低,使用并不需要修改网络请求的代码,所以就算切换掉本框架也不会影响之前写的代码

对于 100MB 以上的大文件的下载,由于下载时间比较长,可能需要有一个独立的 service 专门负责下载,并且支持暂停继续,本地保存下载进度,断点续传,维持请求队列,在网络意外断开时进行重连逻辑,对于大文件来说其实更需要的是文件管理能力,并不只是简单的展示,而这些都是提高用户体验的刚需功能,所以我建议你使用专业的文件下载库

本库比较轻量级,向开发者提供简洁的Api,以便非常容易的实现, 100Mb 以下附件以及图片等资源的下载进度展示

简洁易用轻量是我对这个库今后的定位,不过我会在保持简洁的基础上,尝试着去适配大文件的下载

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/ProgressManager/commit/83f224986677ca1a0a357b9faaeab124a070abe1
