### ISSUE TITLE
上传图片的进度跨度太大  直接从0 14 100 没了 那个mRefreshTime设置了感觉没啥用啊

### ISSUE THREAD

**Issue by CK875430315** [JessYanCoding/ProgressManager#20]

**Comment by JessYanCoding** [comment]
**mRefreshTime** 的功能只是为了防止较快的回调, 而不能加快实际回调的频率, 回调的实际频率是 **Okhttp** 决定的, 比如 **Okhttp** 在执行一个进度的时候, 1 秒回调 10 次, 这时你可以通过控制 **mRefreshTime** 让回调频率变成 1 秒 5 次, 意思是你只能让较快频次的回调变得更加缓慢, 如果 **Okhttp** 他回调的实际频率已经很慢, 导致进度跨度太大, 那 **mRefreshTime** 的用途只能让这个回调变得更慢, 进度跨度更大, 哪怕你把 **mRefreshTime** 设置为 0, 一样无法改变这个问题, 因为实际回调的频率已经每次回调的时间是 **Okhttp** 决定, 如果总上传时间为 1 秒, **Okhttp** 只回调了 3 次, 第一次在开始, 第二次在百分 14, 第三次在结束, 那肯定会出现你的情况
