### ISSUE TITLE
弱引用问题

### ISSUE THREAD

**Issue by TruthKeeper** [JessYanCoding/ProgressManager#21]
WeakHashMap是对Key进行弱引用，并不是对Value吧

**Comment by JessYanCoding** [comment]
是的, 我注释里一直说的是对 key 弱引用, 并且做了详细的介绍

**Comment by JessYanCoding** [comment]
因为 {@link WeakHashMap} 将 {@code key} 作为弱键 (弱引用的键), 所以当 java 虚拟机 GC 时会将某个不在被引用的 {@code key} 回收并加入 {@link ReferenceQueue}, 在下一次操作 {@link WeakHashMap} 时, 会比对 {@link ReferenceQueue} 中的 {@code key}, 将 {@link WeakHashMap} 中对应的 {@code key} 连同 {@code value} 一起移除, 从而免去了手动 {@link Map#remove(Object)}

**Comment by JessYanCoding** [comment]
上面这句话是 **ProgressManager** 的注释中的原话, 不知道你提这个 Issues 上面意思? 就是想告诉我这个吗？

**Comment by TruthKeeper** [comment]
可是监听的时候通常是对Activity等实现ProgressListener接口吧，那不是一直持有上下文了吗

**Comment by JessYanCoding** [comment]
没听懂你说的什么意思
