### ISSUE TITLE
仿微信下载原图的那种效果可以用这个代码实现吗

### ISSUE THREAD

**Issue by mycold** [JessYanCoding/ProgressManager#22]
![image](https://user-images.githubusercontent.com/14937950/33705523-9acdd58c-db6b-11e7-881d-d1cdd5ef9874.png)

**Comment by mycold** [comment]
使用glide去下载图片到本地时，只有下载的开始和结束回调，没有进度监听

**Comment by JessYanCoding** [comment]
本框架和 UI 没有任何关系

**Comment by JessYanCoding** [comment]
只要 Glide 使用的是 Okhttp 进行网络请求, 并且是发起了真实的网络请求, 如果没有缓存或者 Glide 发生了其他情况暂停了下载, 此框架无法解决, 本质就是对 Okhttp 的封装, Glide 它有很多逻辑, 影响了 Okhttp 的下载, 框架是无法解决的
