### ISSUE TITLE
同一个接口上传多个文件时，能否监听到每个文件的上传进度？

### ISSUE THREAD

**Issue by luckyloong** [JessYanCoding/ProgressManager#24]
上传接口类似：

@Multipart
@POST("api/upload")
Observable<HttpBaseJson> upload(@PartMap Map<String, RequestBody> parts);

parts 里面包含了普通的文本参数和多个文件，不知道能否监听具体文件的上传进度，谢谢！目前使用的是您的MVPArms框架

**Comment by JessYanCoding** [comment]
只能监听一个接口的总进度

**Comment by luckyloong** [comment]
好的，谢谢！
