### ISSUE TITLE
为什么不开放mRequestListeners

### ISSUE THREAD

**Issue by tpnet** [JessYanCoding/ProgressManager#25]
例如这样子的一个需求，我从One Activity 监听进度，，打开了TwoActivity开始Service上传，然后 退出TwoActivity，再退出了OneActivity，，，这时候我再进去OneActivity，，怎么获取正在上传的进度？？？

我看了源码，接口在 mRequestListeners里面，但是并没有开放出来。

**Comment by JessYanCoding** [comment]
一个进度开始之前才能添加监听器, 如果一个进度已经开始是不能添加监听器的, 兄弟, 这样设计是为了提升效率, 在这 [里面](https://github.com/JessYanCoding/ProgressManager/issues/19) 有介绍, 我把 mRequestListeners 提供出来是不安全的操作, 没有这样考虑过, 你这种需求, 可以考虑在将监听器放入 Service 中, Service 中的监听器在分发给其他需要通知进度的 Activity
