### ISSUE TITLE
上传

### ISSUE THREAD

**Issue by xymorlLd** [JessYanCoding/ProgressManager#26]
如果想要上传图片。是多张图片。同时还有文本参数。使用你的库可以嘛？没有找到传参的地方。

**Comment by JessYanCoding** [comment]
兄弟, 上传是通过 Okhttp 或者 Retrofit, 这些你自己百度, 这个库只有一个功能就是在上传或下载过程中通知你上传或下载的进度, 至于你怎么上传, 怎么下载和框架无关, 我也不会回答此类基础问题
