### ISSUE TITLE
重定向后，新增进WeakHashMap中entry的回收问题

### ISSUE THREAD

**Issue by LJYcoder** [JessYanCoding/ProgressManager#29]
你好~ 重定向后，会根据重定向的地址新增相关的entry进WeakHashMap中以保证重定向后也可以监听进度，但是新增的entry的key值并没返回给activity或其他实现了listener的类，没返回的话就没办法在退出时置null，不置null的话WeakHashMap中相关的entry没被回收，没被回收就导致了内存泄漏。这样的说法有问题吗？

**Comment by JessYanCoding** [comment]
置为 Null 是因为 Activity 或者 Fragment 全局变量持有这个 Url,  Activity 都拿不到这个 Url 怎么持有这个 Url? 都不持有这个 Url 为什么还需要置为 Null?

**Comment by LJYcoder** [comment]
Actvity实现了listener，并且传进了ProgressManager，ProgressManager是个单例，这样单例中持有了activity，生命周期长的持有了生命周期短的，不是导致了activity无法被正常回收吗？ 
我理解的在listener实现类中将key值置null，是为了让weakHashMap中该key值和key值对应的value值被回收，这样就不会持有了listener的实现类了。

**Comment by JessYanCoding** [comment]
都没有任何变量持有 key  为什么还需要置为 null, 我在 onDestroy 中置为 null, 是因为我在 Activity 持有了这个 key, 如果没有变量持有 key, 那他就会在内存回收的时候被释放, 这个重定向的 key 被创建出来时, 就没有外部任何变量持有他, 那他就会在内存回收时被释放, 为什么还要再去持有他, 然后在给他置为 null

**Comment by LJYcoder** [comment]
恩明白你的意思了。 但这个WeakHashMap在系统内存允许的范围内，不会自动释放没被引用的key及value吧？！ 这样的话不是也有内存泄漏的风险吗？

**Comment by JessYanCoding** [comment]
如果你怕得话，那你使用内部静态类，创建监听器，或者写个单独的非内部类实现监听器

**Comment by LJYcoder** [comment]
好的，谢谢了。
你的一些代码我想拿来自己的开源项目里用，但会标注出处，可以不？

**Comment by JessYanCoding** [comment]
可以的，用于开源项目，我都是支持的，大家相互学习，开源社区才能蓬勃发展
