### ISSUE TITLE
下载进度完成会重复回调

### ISSUE THREAD

**Issue by Joky-SSS** [JessYanCoding/ProgressManager#3]
![image](https://user-images.githubusercontent.com/16696542/27209020-da04dc42-527b-11e7-9408-a8319cc37f2c.png)
通过progressInfo.getContentLength() == progressInfo.getCurrentbytes()这样判断下载完成，最后两次回调结果是相同的，这样会走两次下载完成的逻辑

**Comment by JessYanCoding** [comment]
if(bytesRead==-1 && totalBytesRead==ContentLength){
  //do something
}

**Comment by Joky-SSS** [comment]
bytesRead这个在外部监听器里是拿不到的，外部像progressInfo.getContentLength() == progressInfo.getCurrentbytes()这样来判断下载完成等于会有两次下载完成的事件了，我是提醒一下你，可能你库内部要做下处理。我直接下的代码用的，自己还有些修改

**Comment by JessYanCoding** [comment]
嗯嗯,等下看看

**Comment by JessYanCoding** [comment]
等下把 bytesRead 提供出来,方便开发者计算速度

**Comment by JessYanCoding** [comment]
测试了下,就算-1也会出现两次或以上的回掉,检测出了问题出在使用 Handler 上,已经修复 https://github.com/JessYanCoding/ProgressManager/commit/e4a10c574f9cde20ee678ae8b0b3f37873af3e95
