### ISSUE TITLE
现在网络请求框架都是mvp模式下的okhttp+retrofit+rxjava大框架如果作者能集成起来就更棒啦！

### ISSUE THREAD

**Issue by on199444** [JessYanCoding/ProgressManager#30]
okhttp+retrofit+rxjava是如何进行文件上传下载，和进度监听的呢？

**Comment by JessYanCoding** [comment]
你还是没明白 Okhttp 和 Retrofit 的关系, 支持 Retrofit,  框架根本不需要更改任何一行代码, 因为 Retrofit 就是使用  oKhttp 进行网路请求, 所以一开始本框架就默认支持 Retrofit, 只是我 Demo 没有演示使用 Retrofit 进行网络上传和下载, 并不代表不支持, 至于怎么使用 Retrofit 进行网络上传或下载请百度

你说的 MVP 模式下的 Okhttp+Retrofit+RxJava, 我的 [MVPArms](https://github.com/JessYanCoding/MVPArms) 框架就是此种类型, 它的 Demo 也是默认集成了 ProgressManager 框架
