### ISSUE TITLE
为什么进度监听没有反应，而资源却能下载下来？

### ISSUE THREAD

**Issue by on199444** [JessYanCoding/ProgressManager#31]
已经在onCreate（）里面 注册监听了ProgressManager.getInstance().addRequestListener(mDownloadUrl,getDownloadLister());
![1521018978 1](https://user-images.githubusercontent.com/17316643/37393228-7d016456-27ab-11e8-8e02-b25138b8d68d.jpg)

**Comment by JessYanCoding** [comment]
自己打断点，看监听器成功添加进去没有，监听器添加进去了，是否被调用没有，官方 Demo 和你同样的步骤，为什么它就行而你却不行

**Comment by on199444** [comment]
我自己的写的dome不行，断点打过了。监听器添加进去了。但是Listener没有起作用，资源却能正常下载

**Comment by JessYanCoding** [comment]
自己对比官方 Demo, 看看为什么同样的步骤官方 Demo 就可行, 自己却不可以

**Comment by gaelthas** [comment]
应该是要指定相同的url，也就是在下载前要知道确切的url。请问有没有好的办法在设置监听的时候获取url呢。目前我是手动拼接的，比如get请求，就要拼后面的参数，如果顺序错了也不行
