### ISSUE TITLE
Retrofit issue!

### ISSUE THREAD

**Issue by subbirhosain27** [JessYanCoding/ProgressManager#36]
I'm using retrofit and creating instance of retrofit in this way.so how should I instantiate now?

    private static final String BASE_URL = "base url";
    public static Retrofit retrofit = null;

    public static Retrofit getClient(){
        if(retrofit==null){
            OkHttpClient client = new OkHttpClient.Builder()
                    .addInterceptor(new LoggingInterceptor()).build();

            retrofit = new Retrofit.Builder()
                    .baseUrl(BASE_URL)
                    .client(client)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();

        }
        return retrofit;
    }

**Comment by JessYanCoding** [comment]
···java
ProgressManager.getInstance().with(new OkHttpClient.Builder())
                .build();
```
With the above code, the framework will run, Retrofit's instantiation has nothing to do with the framework
