### ISSUE TITLE
如果我不想要多个监听器，应该怎么样操作呢？

### ISSUE THREAD

**Issue by tpnet** [JessYanCoding/ProgressManager#39]
有个需求是这样子的，下载监听只要一个 ，，但是现在的情况是这样子的，应用会因为某些原因会重复addResponseListener相同的url，这样子就会导致onProgress同时回调多次，，但是我想只回调后面那一次。

我在demo把addResponseListener复制多了一行，然后下载的时候，onProgress每次回调都会回调两次，我是想覆盖的。但是addResponseListener并没有覆盖的

**Comment by JessYanCoding** [comment]
这个是你自己使用上的问题了，没有覆盖这一说，框架本来就支持一个 key，多个监听器，每个 key 都对应一个容器，所以根本不允许覆盖，覆盖了那还怎么支持一对多的关系

**Comment by tpnet** [comment]
嗯，需求主要就是想只使用一个容器监听器，我自己加个方法解决吧:
`
    /**
     * 将需要被监听下载进度的 {@code url} 注册到管理器,唯一监听器
     *
     * @param url      {@code url} 作为标识符
     * @param listener 当此 {@code url} 地址存在下载的动作时,此监听器将被调用
     */
    public void addCoverResponseListener(String url, ProgressListener listener) {
        checkNotNull(url, "url cannot be null");
        checkNotNull(listener, "listener cannot be null");
        List<ProgressListener> progressListeners;
        synchronized (ProgressManager.class) {
            progressListeners = mResponseListeners.get(url);
            if (progressListeners == null) {
                progressListeners = new LinkedList<>();
                mResponseListeners.put(url, progressListeners);
                progressListeners.add(listener);
            }else{
                progressListeners.clear();
                progressListeners.add(listener);
            }
        }
    }
`

**Comment by JessYanCoding** [comment]
嗯，那你自己改把，这个是框架最初的设计就是要解决一对多这个需求的的，所以费了这么多周折支持了一对多是不可能再改成一对单的，这相当于退步
