### ISSUE TITLE
感觉没用啊  你试下这个连接 没啥反应

### ISSUE THREAD

**Issue by 13787386507** [JessYanCoding/ProgressManager#40]
http://datamarketapi.apyfc.com/api/bos/downloadfile?objectName=201811021621458048561.ppt

**Comment by JessYanCoding** [comment]
看了下，下载的时候有进度信息，但是进度一直为 0，日志信息为 currentBytes=10745468, contentLength=-1，断点进去看了，是服务器没有返回这个数据的总大小，在服务器没有返回数据总大小的情况下，框架只能获取到当前已经下载了多少数据，使用 **总大小/除以当前已下载数据大小** 这个公式，由于总大小未知，所以根本不可能能算出进度，所以这个问题和框架无关，框架不可能在数据还未下载完成之前就知道数据的总大小，必须依赖服务器的返回，至于服务器的问题，自己想办法吧，框架无能为力
