### ISSUE TITLE
ProgressListener的onError方法为什么不在主线程回调

### ISSUE THREAD

**Issue by magic0908** [JessYanCoding/ProgressManager#41]
在ProgressRequestBody和ProgressResponseBody里，只有成功的时候才是主线程，但是错误的的时候却只是回调出来，没做线程切换处理。
demo中是在activity创建一个Handler，然后在listener的onError中切换到主线程更新UI。这样会导致使用到上传的界面都需要创建Handler处理onError的回调。

**Comment by JessYanCoding** [comment]
我当时考虑的是当 onError 时，用户不一定都会做 UI 操作，有一半的可能会做其他非 UI 的操作，所以没在框架中默认将 onError 切换为主线程，而 Demo 为了更好的展示所以将错误信息显示到了 UI  界面上，所以使用到了 Handler，当然也可以使用 RxJava 切换线程

**Comment by JessYanCoding** [comment]
报错，已经说明问题了，不懂就百度下
