### ISSUE TITLE
okhttp3.10和3.13回调未执行，不清楚怎么回事

### ISSUE THREAD

**Issue by crykid** [JessYanCoding/ProgressManager#42]

**Comment by crykid** [comment]
不好意思没有说清楚，ProgressListener，这个未执行，我换到okhttp3.8好了

**Comment by JessYanCoding** [comment]
兄弟才试了的哈，在官方 Demo 上 v3.10  v3.12，都可以完美运行的哈，v3.13 不晓得你在哪下的，貌似 Okhttp 官方最新稳定版本是 v3.12，你自己试试 ProgressManager 的官方 Demo，对比下和自己项目有差别的地方，自己打断点看看监听器容器里面是否未注册成功
