### ISSUE TITLE
Glide 小图片 加载

### ISSUE THREAD

**Issue by c594701048** [JessYanCoding/ProgressManager#43]
图片直接加载出来 回调进度值为0 isFinish=false ,

**Comment by c594701048** [comment]
调试发现 下发的资源做GZip操作，相应的content-length=-1
改成 Request.Builder().addHeader("Accept-Encoding", "identity") 就正常了

**Comment by c594701048** [comment]
GlideUrl glideUrl = new GlideUrl(config.getUrl(), new LazyHeaders.Builder()
				.addHeader("Accept-Encoding", "identity")
				.build());

**Comment by JessYanCoding** [comment]
👍🏻
