### ISSUE TITLE
使用retrofit上传无法监听

### ISSUE THREAD

**Issue by androidmh** [JessYanCoding/ProgressManager#45]
下载监听是没问题的，但是上传怎样都无法监听的，我对照源码也配置了okhttp的client，val builder = ProgressManager.getInstance().with(OkHttpClient.Builder())，但是就是不管怎样都监听不到上传进度

**Comment by androidmh** [comment]
看到了您说的只要这个 {@code url} 存在上传 (请求时有 {@link RequestBody})，我的上传是这样的 @Multipart
    @POST("image")
    fun uploadImage(@Part img: MultipartBody.Part,@PartMap() map:MutableMap<String,RequestBody>): Observable<BaseResp<Any>>，难道是没有监听到requsetBody？

**Comment by JessYanCoding** [comment]
1.断点看下是否注册成功，框架中的监听器容器，是否有你注册的监听器，
2.断点在 okhttp 的拦截器看下，拦截器中的 ProgressRequestBody 是否在对应请求时调用了监听器

**Comment by JessYanCoding** [comment]
框架源码比较简单，只要确认问题是出在，注册阶段还是调用阶段，就可以确认问题

**Comment by androidmh** [comment]
注册的时候应该没有问题，我在想是不是因为我的接口是图文上传的，而我的图片用的是MultipartBody.Part，所以导致没有监听到

**Comment by JessYanCoding** [comment]
如果注册成功，这一步没问题，出在调用这里，就需要你自己排查了，因为整个调用时机的主动权在 okhttp 的拦截器中，如果 okhttp 的拦截器，在这个请求中没有被主动调用，那 ProgressManager 监听器也就不无法被调用，这时 ProgressManager 也就没有任何办法，ProgressManager 只负责管理监听器，数据源还是要依赖于 okhttp，所以你需要自己排查关于 okhttp 的问题

**Comment by androidmh** [comment]
嗯，我觉得也是okhttp拦截器的问题，但是我还没有找到，我尝试着用您的代码将上传的接口改为了我的接口，因为我的文件上传是键值对，
所以改写了代码，
![image](https://user-images.githubusercontent.com/29589577/49709626-4d680700-fc70-11e8-983d-f10a3b63faf0.png)
当然上传接口也是我的接口，
![image](https://user-images.githubusercontent.com/29589577/49709593-26113a00-fc70-11e8-9978-a8ad00299807.png)，
上传成功了，但是进度一样没有监听到，是我接口的问题吗

**Comment by androidmh** [comment]
问题解决了，我看了半天您的源码，最后发现是okhttp的问题，由于我的服务器还没用部署到外网，所以本地使用了80端口（其实即使在外网也没有买域名），因为在baseurl里拼接了:80端口所以导致监听不到，目前还没有发现为什么加了端口就无法监听进度，但是确实把端口去掉就可以监听进度了

**Comment by JessYanCoding** [comment]
你断点看下，拦截器中拿到的网络地址，是否含有端口号，断点 [这个位置](https://github.com/JessYanCoding/ProgressManager/blob/master/progress/src/main/java/me/jessyan/progressmanager/ProgressManager.java#L139)

看看是否这里用于取监听器的 key 含有端口号，而之前用于注册监听器的 key 却没有端口号，导致 key 不匹配，所以没取到想取的监听器，如果是这个问题，加上端口号，保证注册时的 key 和 取时的 key 一致即可解决问题

**Comment by androidmh** [comment]
我调试了一下，我用的是同一个key，而且注册和mRequestListeners.get(url)这个位置的url都显示含有端口号的，但是就是监听不到

**Comment by androidmh** [comment]
我看了一下，不是端口号的问题，好像是缓存的问题，因为我需要不停的发布服务器的版本，所以baseURL要在服务器的地址和本地的不停切换
![image](https://user-images.githubusercontent.com/29589577/49715241-b3fa1e80-fc8a-11e8-902e-f924cad19a66.png)，当我切换到本地调试的时候，这个方法
![image](https://user-images.githubusercontent.com/29589577/49715259-c2483a80-fc8a-11e8-95d4-a056b8febbc4.png)的返回值居然是服务器的地址，但是我注册的时候注册的是本地的地址，我以为是缓存的问题，我发应用清除缓存后发现这个方法获取的地址还是我服务器上的地址，所以对应不上

**Comment by JessYanCoding** [comment]
你截图中的这个 **url**，是在 okhttp 拦截器中从 **request** 中获取的，至于为什么你说的你请求的是本地地址，但是 okhttp 拦截器却表示这次请求的是服务器地址，这个就需要你去深入 debug 了，不过问题已经确认了，就是 注册时的 key 和 取时的 key 不一致导致的，你只要能保证一致即可解决问题，不过据我对 Retrofit 源码的了解，baseUrl  貌似没有缓存这一说
