### ISSUE TITLE
使用retrofit上传文件监听问题

### ISSUE THREAD

**Issue by chenxi0203** [JessYanCoding/ProgressManager#46]
在某个界面选择文件上传，能显示进度条进度，这时候取消上传，在选择该文件上传，也能显示进度条进度，但是当取消上传后退出该界面，在进入页面选择该文件上传时进度条不起作用。请问这个怎么解决？

**Comment by chenxi0203** [comment]
而且是隔一次好一次，这次不起作用时，退出该界面进入在重新上传又可以了，在退出在进来又不行了。使用的是mDisposable.dispose();取消的请求，ondestory 里面 mUploadUrl 置空了。

**Comment by chenxi0203** [comment]
url置空去掉就行了。

**Comment by chenxi0203** [comment]
暂时还没查直接把mUploadUrl = null  去掉是否会有内容泄露的问题

**Comment by chenxi0203** [comment]
@JessYanCoding   能否解答下！！！！

**Comment by JessYanCoding** [comment]
不会内存泄漏哈，mUploadUrl 并没有引用当前 Activity，只是手动 mUploadUrl = null 可以更利于 WeakHashMap 中值的回收
