### ISSUE TITLE
我这样使用时发现内存泄漏情况

### ISSUE THREAD

**Issue by coolstar1204** [JessYanCoding/ProgressManager#47]
`Class Name                                                                                                                          | Shallow Heap | Retained Heap
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
cn.kuwo.boom.ui.make.ClipsHotPicFragment @ 0x1300cc88                                                                               |          280 |         1,536
'- this$0 cn.kuwo.boom.ui.make.ClipsHotPicFragment$2 @ 0x1300cc28                                                                   |           16 |            16
   '- val$listener cn.kuwo.boom.http.down.Downloader$1 @ 0x1300cc18                                                                 |           16 |            32
      '- item java.util.LinkedList$Node @ 0x1300cc00                                                                                |           24 |            56
         '- first, last java.util.LinkedList @ 0x1300cbe8                                                                           |           24 |            80
            '- value java.util.WeakHashMap$Entry @ 0x1300cbc0                                                                       |           40 |           216
               '- [7] java.util.WeakHashMap$Entry[16] @ 0x1300cb70                                                                  |           80 |           296
                  '- table java.util.WeakHashMap @ 0x1300cb28                                                                       |           48 |           376
                     '- mResponseListeners me.jessyan.progressmanager.ProgressManager @ 0x1300cab8                                  |           32 |           600
                        |- mProgressManager class me.jessyan.progressmanager.ProgressManager @ 0x12e2b8f8 System Class, Native Stack|           32 |           168
                        |- this$0 me.jessyan.progressmanager.ProgressManager$1 @ 0x1300caa0                                         |           16 |            16
                        '- Total: 2 entries                                                                                         |              |              
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
`

使用方式
`ProgressManager.getInstance().addResponseListener(url, new ProgressListener(){

            @Override
            public void onProgress(ProgressInfo progressInfo) {
                Log.d(TAG, "file download: " + progressInfo.getCurrentbytes() + " of " + progressInfo.getContentLength());
                if(listener!=null){
                    listener.onDownloadProcess(url,progressInfo.getPercent());
                }
            }

            @Override
            public void onError(long id, Exception e) {
                Log.d(TAG,"error:"+e.getMessage());
                if (listener != null) {
                    listener.onDownloadFailed(url, -2, "" + e.getMessage());
                }
            }
        });`

**Comment by coolstar1204** [comment]
不能传图片，mat的信息格式不如图片好看。抱歉

**Comment by JessYanCoding** [comment]
你好，这里的 [注释](https://github.com/JessYanCoding/ProgressManager/blob/master/app/src/main/java/me/jessyan/progressmanager/demo/MainActivity.java#L72) 有看过吗，需要根据这里的提示去操作才能释放引用
