### ISSUE TITLE
建议增加和Glide类似的方式二次监听相同的url方式

### ISSUE THREAD

**Issue by walkthehorizon** [JessYanCoding/ProgressManager#48]
如下    
public void addResponseListener(String url, ProgressListener listener) {
        List<ProgressListener> progressListeners;
        synchronized (ProgressManager.class) {
            progressListeners = mResponseListeners.get(url);
            if (progressListeners == null) {
                progressListeners = new LinkedList<>();
                mResponseListeners.put(url, progressListeners);
            }
        }
        progressListeners.add(listener);
    }
，这里我看到接收到相同的url时，直接把之前的progressListeners重新放到监听了，我觉得可以再增加一个方法，逻辑上是先删除之前已有的，再把新的加进去，具体使用哪个让开发者自由选择

**Comment by JessYanCoding** [comment]
一个就够了，你需要两个逻辑在 ProgressListener 自己分发和选择需要的逻辑就可以了
