### ISSUE TITLE
关于FormBody上传Base64的问题

### ISSUE THREAD

**Issue by bailandi** [JessYanCoding/ProgressManager#49]
- 请问使用FormBody作为请求体的Post请求上传转成base64字符串的图片可以监听进度吗？
我尝试发现进度总是一次就完成，contentLength大约在1M左右。

- 另外就是关于上传进度的问题，在模拟弱网的测试下，上传进度已经完成，但是等待response超时，这样图片算是上传成功吗？

**Comment by JessYanCoding** [comment]
你好，关于上传以及下载的具体操作是 Okhttp 完成的，ProgressManager 只是负责把 Okhttp 提供的参数展示出来，所以不管你通过什么方式，上传什么格式的内容，只要 Okhttp 能支持，并且可以提供上传参数，ProgressManager 就能监听
