### ISSUE TITLE
glide加载图片百分比进度跨越太大，几乎直接跳到100，能不能做得平缓一点

### ISSUE THREAD

**Issue by tdxtxt** [JessYanCoding/ProgressManager#5]

**Comment by JessYanCoding** [comment]
是你自己网速太快,你自己想想,我只要保证实际下载时间和显示进度同步,就不可能做到你说的平缓一点,我怎么做,难道你1秒时间就下载完了,我在延迟一秒,将速度分摊到多的这一秒?

**Comment by JessYanCoding** [comment]
用户体验的事,你觉得有必要付出时间去做,你就只有你自己做咯,我肯定不会为了用户体验,放弃进度显示时间与实际下载时间的同步

**Comment by tdxtxt** [comment]
恩，看你源码，是你REFRESH_TIME值200ms，设置小一点就可以了

**Comment by JessYanCoding** [comment]
哦哦,刚刚没理解你的意思,原来你这个意思,后面我会把这个时间提供出来

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/ProgressManager/commit/66e1cfb02854f52d2a2cdc7db87fbf360d6cfa8a     **setRefreshTime()** 可多次调用,你在请求前调用,就可以将后面的所有请求的刷新时间改变
