### ISSUE TITLE
有些地址监听下载进度无效，getPercent()=0

### ISSUE THREAD

**Issue by xilost** [JessYanCoding/ProgressManager#50]
如下地址监听下载进度，getPercent()一直为0
http://test.api.hd.weibo.com/appapi/adreappear/generate?id=60486&useruid=2883796890&operator=中国电信&date=2018-06-22&time=10%3A00&battery=85&network=wifi&topline=0&forward=&comment=&praise=&nickname=RedDevil_Gaal&equipment=android

**Comment by JessYanCoding** [comment]
参考下这个 [issues](https://github.com/JessYanCoding/ProgressManager/issues/40)，可能是服务器没返回正确的 contentLength，自己断点看下

**Comment by xilost** [comment]
![image](https://user-images.githubusercontent.com/5326618/54879920-f03c3e00-4e79-11e9-80be-ef7b07b88e3a.png)

查了下header，contentLength有值的。

**Comment by JessYanCoding** [comment]
那你打下断点，看下框架是否取到了 contentLength 的正确值，如果取到了，再断点看下是否是计算 Percent 时，出现了错误
