### ISSUE TITLE
自定义的ImageView里面设置图片监听导致内存泄漏，该如何避免呢？

### ISSUE THREAD

**Issue by lookballs** [JessYanCoding/ProgressManager#51]
/**
     * 设置加载网路图片
     *
     * @param imageUrl
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
        //getGlideLoadListener(imageUrl); TODO 此处这样使用会导致内存泄漏
        GlideImageUtil.showImage(imageUrl, this);
    }

    /**
     * okhttp/Retofit 图片加载监听
     */
    private void getGlideLoadListener(String imageUrl) {
        ProgressManager.getInstance().addResponseListener(imageUrl, new ProgressListener() {
            @Override
            public void onProgress(ProgressInfo progressInfo) {
                LogUtil.i("rudni_图片加载进度", "已加载：" + progressInfo.getPercent());
                if (progressInfo.isFinish()) {
                    LogUtil.i("rudni_图片加载进度", "加载完成");
                }
            }

            @Override
            public void onError(long id, Exception e) {
                LogUtil.i("rudni_图片加载进度", "图片加载失败：" + e.getMessage());
            }
        });
    }

**Comment by JessYanCoding** [comment]
内存泄漏的具体信息有吗

**Comment by lookballs** [comment]
leakcanary检测到的内存泄漏信息

* Reference Key: 37f65376-c147-41a1-b866-150f7014b201
* Device: Xiaomi Xiaomi Redmi 5A riva
* Android Version: 7.1.2 API: 25 LeakCanary: 1.6.3 31007b4
* Durations: watch=5012ms, gc=154ms, heap dump=2535ms, analysis=31436ms
* Excluded Refs:
| Field: android.os.Message.obj
| Field: android.os.Message.next
| Field: android.os.Message.target
| Field: android.view.inputmethod.InputMethodManager.mNextServedView
| Field: android.view.inputmethod.InputMethodManager.mServedView
| Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
| Field: android.view.inputmethod.InputMethodManager.mCurRootView
| Field: android.accounts.AccountManager$AmsTask$Response.this$1
| Field: android.os.UserManager.mContext
| Field: com.android.internal.policy.BackdropFrameRenderer.mDecorView
| Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
| Thread:FinalizerWatchdogDaemon (always)
| Thread:main (always)
| Thread:LeakCanary-Heap-Dump (always)
| Class:java.lang.ref.WeakReference (always)
| Class:java.lang.ref.SoftReference (always)
| Class:java.lang.ref.PhantomReference (always)
| Class:java.lang.ref.Finalizer (always)
| Class:java.lang.ref.FinalizerReference (always)

**Comment by JessYanCoding** [comment]
报错信息没有指向我这个库，指向的是 InputMethodManager 这个东西，所以不是框架的问题

**Comment by lookballs** [comment]
但是确实是加了你这个东西后才会发生内存泄漏，去除后又不会

**Comment by lookballs** [comment]
我这边又给不了更多的信息，尴尬

**Comment by JessYanCoding** [comment]
看下[这](https://github.com/JessYanCoding/ProgressManager/blob/master/progress/src/main/java/me/jessyan/progressmanager/ProgressManager.java#L55) 和 [这](https://github.com/JessYanCoding/ProgressManager/blob/master/app/src/main/java/me/jessyan/progressmanager/demo/MainActivity.java#L76)，还不行的话，我建议用 AS 看下内存中的信息，看实际的引用情况，InputMethodManager 这个东西你可以百度下相关的案例，很多情况下 InputMethodManager 的引用是无解的，是个系统 BUG
