### ISSUE TITLE
比较急，关于Glide第二次加载同一张图片，因为Glide做了缓存，没有走进度回调的问题

### ISSUE THREAD

**Issue by yaochangliang159** [JessYanCoding/ProgressManager#6]
如果是Glide第一次加载图片，一切运行正常，进度回调能够正常执行
不过我第二次打开我的界面，因为glide已经加载过一次了，glide默认对图片做了缓存，这样导致直接不走进度回调，因为我需要 进度回调 来操作我UI界面上的一些空间，显示或者不显示，比如操作progressbar的现实与隐藏，由于不走回调，我的progressbar只能一直显示在界面上。
我看你的DEMO代码里，加载图片不做缓存，这样演示确实比较方便，可是，一个项目的图片还是要做缓存的吧，，，这是你的演示代码
  Glide.with(this)
                .load(IMAGE_URL)
                .centerCrop()
                .placeholder(R.color.colorPrimary)
                .diskCacheStrategy(DiskCacheStrategy.NONE)
                .into(mImageView);
求助？在Glide第二次加载图片的时候，我该如何控制我的progressbar的显示与隐藏？

**Comment by JessYanCoding** [comment]
我是依赖于 **Okhttp** 的拦截器而实现 **Glide** 的进度监听, 如果 **Glide** 使用缓存,根本就不会走拦截器,不走拦截器,我的 **Api** 根本不知道你什么时候调用的 **Glide** 开始加载图片,这样的好处也是请求端和接收端毫无耦合,你如果想依赖于我的 **Api** 实现你上面所说的逻辑,那我能想到的就是在 **onProgress** 中 **currentBytes** 开始不为0的时候,就显示进度,在 **currentBytes == contentLength** 或者报错时,隐藏进度条

**Comment by yaochangliang159** [comment]
感谢感谢，总算是有解决方法了

**Comment by JessYanCoding** [comment]
如果不依赖于我的 **Api** 实现你说的显示隐藏,通过 **Glide** 来达到你的需求,是最简单的,因为 **Glide** 肯定知道你什么时候开始请求,什么时候请求完毕,我没记错的话 **Glide** 又一个监听器,你百度下

**Comment by yaochangliang159** [comment]
Glide.with(this)
                .load(url)
                .fitCenter()
                .listener(new RequestListener() {

                    @Override
                    public boolean onException(Exception arg0, Object arg1,
                                               Target arg2, boolean arg3) {
                        T.show("加载图片出错");
                        progress_bar.setVisibility(View.GONE);
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(Object arg0, Object arg1,
                                                   Target arg2, boolean arg3, boolean arg4) {
                        progress_bar.setVisibility(View.GONE);
                        return false;
                    }
                })
                .into(imageview);
你说的进度监听是这个吗？这个只能监听加载完成，加载失败，无法精准监听具体下载到多少进度了，我现在的需求是要做一个类似新浪微博浏览图片时候 中间一个圆圈转满  就代表图片加载完成，所以需要监听图片具体下载到的progress

**Comment by JessYanCoding** [comment]
你调用 **Glide** 的时候, **View.VISABLE** , **listener** 里面 **View.GONE** ,我的 **onProgress** ,来控制显示进度,显示时给个判断 **Statu==View.VISABLE** ,有问题吗？ 或者重写 **Target** ,或者使用我上面说到的方法,我觉得应该不难吧,实现还不止一种

**Comment by JessYanCoding** [comment]
你调用 **Glide** 的时候, **View.VISABLE** , **listener** 里面 **View.GONE** ,我的 **onProgress** ,来控制显示进度,显示时给个判断 **Statu==View.VISABLE** ,有问题吗,或者重写 **Target** ,或者使用我上面说到的方法,我觉得应该不难吧,实现还不止一种

**Comment by yaochangliang159** [comment]
哎呀。。我怎么没想到glide监听控制显示不显示，然后用你的api控制进度的加载。。。我真是秀逗了。T_T！

**Comment by JessYanCoding** [comment]
你还差点劲道😝
