### ISSUE TITLE
PUT PATCH support for updating while uploading

### ISSUE THREAD

**Issue by Dreamersoul** [JessYanCoding/ProgressManager#8]
progress is not being updated for some reason when using put or patch
does the library support them and i am doing something wrong?

**Comment by JessYanCoding** [comment]
ProgressManager don't care what you use http method,just Okhttp works correctly, ProgressManager will be able to work

**Comment by Dreamersoul** [comment]
Thanks for the reply! I don't know why it didn't work for me, I'll keep digging
Thank you for this awesome project closing the issue now

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
