### ISSUE TITLE
请问如何获取回下载记录，跟删除下载记录呢

### ISSUE THREAD

**Issue by littleHandSome** [JessYanCoding/ProgressManager#9]
> 请问如何获取回下载记录，跟删除下载记录呢

**Comment by JessYanCoding** [comment]
下载记录,这些不是我这个框架涉及到的功能,这些应该是专业的下载库去用数据库实现的功能,而我这个轻量库,只是方便开发者使用简洁的 **Api** 更简单的实现进度监听, see [RxDownload](https://github.com/ssseasonnn/RxDownload) and [FileDownloader](https://github.com/lingochamp/FileDownloader)

**Comment by littleHandSome** [comment]
好的呀
